keboola/google-analytics-extractor

src/Keboola/GoogleAnalyticsExtractor/Application.php
src/Keboola/GoogleAnalyticsExtractor/Extractor/Extractor.php
src/Keboola/GoogleAnalyticsExtractor/Extractor/Output.php
tests/Keboola/GoogleAnalyticsExtractor/Extractor/OutputTest.php

Fixes #34 
- reorganized some output functions (separated to allow usage in json sample function)
- new function and action to get sample data as json

Json sample report

---

.travis.yml
composer.json
composer.lock
docker-compose.yml
src/Keboola/GoogleAnalyticsExtractor/Logger/LineFormatter.php

FIXES https://github.com/keboola/google-analytics-extractor/issues/37

Update to Google Client Bundle 4.6

---

src/Keboola/GoogleAnalyticsExtractor/GoogleAnalytics/Client.php
tests/Keboola/GoogleAnalyticsExtractor/ApplicationTest.php
tests/data/config_mcf.json

https://developers.google.com/analytics/devguides/reporting/mcf/v3/reference#response_fields

fix (MCF): parse correctly the response with conversionPath data type

---

src/Keboola/GoogleAnalyticsExtractor/GoogleAnalytics/Client.php
tests/data/config.json
tests/data/config_antisampling.json
tests/data/config_mcf.json

- FIXES https://github.com/keboola/google-analytics-extractor/issues/47
- also I needed to change the testing accounts and profiles as Keboola Website now uses different ones

MCF: Response Too Large fix

---

src/Component.php
src/Configuration/ConfigGetProfilesPropertiesDefinition.php
src/Extractor/Extractor.php
src/GoogleAnalytics/Client.php
tests/Keboola/GoogleAnalyticsExtractor/ApplicationTest.php
tests/Keboola/GoogleAnalyticsExtractor/Extractor/ExtractorTest.php
tests/data/config_empty.json

Jira - https://keboola.atlassian.net/browse/COM-811
- Získávání profilů pro UIčko přes sync akci
- nově je tu získávání "Properties" které bude sloužit k https://github.com/keboola/google-analytics-extractor/pull/55

add sync action "getProfilesProperties"

---

src/Extractor/Antisampling/AntisamplingProfile.php
src/Extractor/Antisampling/AntisamplingProperty.php
src/Extractor/Antisampling/IAntisampling.php
src/Extractor/Extractor.php
src/GoogleAnalytics/Client.php
tests/Keboola/GoogleAnalyticsExtractor/GoogleAnalytics/AntisamplingProfileTest.php
tests/Keboola/GoogleAnalyticsExtractor/GoogleAnalytics/AntisamplingPropertyTest.php
tests/Keboola/GoogleAnalyticsExtractor/GoogleAnalytics/AntisamplingTest.php

Jira - https://keboola.atlassian.net/browse/COM-836
Je přidaná podpora pro `dailyWalk` sampling... `adaptive` který je ze strany GA není v Data API dostupná

Add antisampling dailyWalk for Account Properties

---

src/Component.php

Pro properties je jiný primaryKey

fix properties primaryKey

---

src/Extractor/Extractor.php

https://keboola.slack.com/archives/C09U3R1J4/p1622195507001600

Fix property antisampling

---

src/Extractor/Extractor.php
tests/Keboola/GoogleAnalyticsExtractor/Extractor/ExtractorTest.php

Jira - https://keboola.atlassian.net/browse/COM-867

Properties filter

---

src/GoogleAnalytics/Client.php
tests/Keboola/GoogleAnalyticsExtractor/Extractor/ExtractorTest.php

Jira - https://keboola.atlassian.net/browse/COM-898

Fix empty profiles/properties

---

phpstan.neon
src/Component.php
src/Configuration/Config.php
src/Configuration/ConfigDefinition.php
src/Configuration/OldConfigDefinition.php
src/Extractor/Extractor.php
src/Extractor/Output.php
tests/Keboola/GoogleAnalyticsExtractor/ApplicationTest.php
tests/Keboola/GoogleAnalyticsExtractor/Extractor/ExtractorTest.php
tests/Keboola/GoogleAnalyticsExtractor/Extractor/OutputTest.php
tests/Keboola/GoogleAnalyticsExtractor/GoogleAnalytics/AntisamplingProfileTest.php
tests/Keboola/GoogleAnalyticsExtractor/GoogleAnalytics/AntisamplingPropertyTest.php
tests/data/config.json
tests/data/config_antisampling.json
tests/data/config_antisampling_adaptive.json
tests/data/config_mcf.json
tests/data/config_old.json
tests/data/config_properties.json

Jira - https://keboola.atlassian.net/browse/COM-1327

Support non-configRow configurations

---

src/Component.php

špatně se nám ukládají profily a property

add destination to profiles/properties manifest files

---

src/Component.php

Sample akce podporovaly jen configRow - projevilo se to jen v sync akcích

Fix sample actions

---

src/Extractor/Output.php
src/Extractor/Validator.php
tests/Keboola/GoogleAnalyticsExtractor/ApplicationTest.php

https://keboola.zendesk.com/agent/tickets/21057
https://keboola.zendesk.com/agent/tickets/21058
https://keboola.slack.com/archives/C09U3R1J4/p1643985237263019

Fix date dimension & List of Profiles

---

.github/workflows/push.yml
composer.json
composer.lock
docker-compose.yml
phpstan.neon
src/Component.php
src/Configuration/Config.php
src/Configuration/MigrateConfiguration.php
src/Configuration/OldConfigDefinition.php
tests/Keboola/GoogleAnalyticsExtractor/Configuration/MigrateConfigurationTest.php

Jira - https://keboola.atlassian.net/browse/COM-1328

Automatic migrate config -> configRow 

---

src/Configuration/MigrateConfiguration.php
tests/Keboola/GoogleAnalyticsExtractor/Configuration/MigrateConfigurationTest.php
tests/data/config_properties.json

https://keboola.slack.com/archives/CQ1ASK06M/p1644583023675579?thread_ts=1644573119.380639&cid=CQ1ASK06M

Row must be in parameters

---

src/Configuration/MigrateConfiguration.php
tests/Keboola/GoogleAnalyticsExtractor/Configuration/MigrateConfigurationTest.php

Slack - https://keboola.slack.com/archives/CQ1ASK06M/p1645013601149919?thread_ts=1644573119.380639&cid=CQ1ASK06M

Remove id from row

---

src/Component.php
src/Configuration/Config.php
src/Configuration/ConfigDefinition.php
tests/Keboola/GoogleAnalyticsExtractor/ApplicationTest.php
tests/data/config_properties.json

Jira - https://keboola.atlassian.net/browse/COM-1395

Recognized run profiles/properties

---

src/Configuration/ConfigDefinition.php
tests/Keboola/GoogleAnalyticsExtractor/Configuration/ConfigDefinitionTest.php

tím že jsme v předchozím PR přidali endpoint na `data-api` tak tohle potřebujeme povolit

fix config definitions

---

src/Component.php
src/Configuration/Config.php
tests/Keboola/GoogleAnalyticsExtractor/Configuration/ConfigDefinitionTest.php

https://keboola.slack.com/archives/C011BERCEBG/p1646643292585859

fix LastRunState config

---

src/Extractor/Extractor.php
tests/Keboola/GoogleAnalyticsExtractor/Extractor/ExtractorTest.php

https://keboola.slack.com/archives/CQ1ASK06M/p1646760053434429

Catch disabled API exceptions

---

src/Extractor/Extractor.php
tests/Keboola/GoogleAnalyticsExtractor/Extractor/ExtractorTest.php

Jira - https://keboola.atlassian.net/browse/COM-1403

get eCommerceTracking in profilesProperties action

---

src/Configuration/ConfigDefinition.php
src/Configuration/OldConfigDefinition.php
tests/data/config.json

https://keboola.slack.com/archives/CQ1ASK06M/p1647272159817029

Fix profile extraKeys

---

composer.lock
src/Configuration/ConfigDefinition.php
tests/Keboola/GoogleAnalyticsExtractor/Configuration/ConfigDefinitionTest.php

Jira - https://keboola.atlassian.net/browse/COM-1448
pouze pro nové `configRow`
aktualizace kritických balíčků podle https://github.com/keboola/google-analytics-extractor/security

automatically add ga:segment to the dimensions

---

phpstan.neon
src/Component.php
src/Configuration/Config.php
src/Configuration/OldConfigDefinition.php
tests/Keboola/GoogleAnalyticsExtractor/ApplicationTest.php

Jira - https://keboola.atlassian.net/browse/COM-1472

Automatically migrate config to configRow

---

composer.lock

JIRA: https://keboola.atlassian.net/browse/COM-1550

Update keboola/google-client-bundle for improved logging

---

src/Extractor/Paginator/PropertiesPaginator.php

https://keboola.atlassian.net/browse/COM-1464?focusedCommentId=44202

fix properties row counter

---

README.md
src/Component.php

JIRA: https://keboola.atlassian.net/browse/COM-1540
Měl jsem tam na to datadir test, ale tím, že pak ve `state.json` nemůžu použít zástupný znaky, tak to nejde použít, když se `today` převede na absolutní datum

Fix fetching with relative dates

---

src/GoogleAnalytics/Client.php

Jira https://keboola.atlassian.net/browse/COM-1540

More logging dateRanges

---

composer.json
src/GoogleAnalytics/Client.php
tests/Keboola/GoogleAnalyticsExtractor/Extractor/ExtractorTest.php
tests/Keboola/GoogleAnalyticsExtractor/Extractor/ValidatorTest.php

JIRA: https://keboola.atlassian.net/browse/COM-1712
Takhle to projde včas, testováno přes tag přímo na tom problematickém velkém projektu z ticketu

Pagination for properties

---

composer.json
composer.lock

JIRA: https://keboola.atlassian.net/browse/CM-85

Update google client bundle

---

composer.json
composer.lock

Jira - https://keboola.atlassian.net/browse/CM-366

update keboola/google-client-bundle package

---

tests/Keboola/GoogleAnalyticsExtractor/GoogleAnalytics/AntisamplingPropertyTest.php

API specs were changed (Please remove pageviews to make the request compatible. See https://developers.google.com/analytics/devguides/reporting/data/v1/announcements/20221201-compatibility-changes)

Fix api change in tests

---

src/Extractor/Extractor.php
tests/functional/get-profile-properties-sync-action-error-handling/expected-stdout
tests/functional/get-profile-properties-sync-action-error-handling/source/data/config.json

JIRA: https://keboola.atlassian.net/jira/software/projects/CM/boards/191?selectedIssue=CM-374

Sync action error handling

---

src/Component.php

JIRA: https://keboola.atlassian.net/browse/CM-512

Change broken token data application exception to user exception

---

src/Configuration/ConfigDefinition.php
src/Extractor/Paginator/PropertiesPaginator.php
src/GoogleAnalytics/Client.php

https://keboolaglobal.slack.com/archives/C055HSSLLKD/p1684830799146589

Fix paginator + maxResults

---

composer.json
composer.lock

Jira - https://keboola.atlassian.net/browse/CM-639
test job - https://connection.keboola.com/admin/projects/6231/queue/981119204

update keboola/php-component package

---

composer.json
composer.lock
tests/Keboola/GoogleAnalyticsExtractor/GoogleAnalytics/ClientTest.php

JIRA: https://keboola.atlassian.net/browse/CM-649
Dal jsem pro teď base branch tu z druhého PR, protože je tam fixnutý ten test. Až se to mergne do masteru, tak to rebasnu.

Retry on unknown metric

---

src/Component.php
tests/Keboola/GoogleAnalyticsExtractor/GoogleAnalytics/AntisamplingProfileTest.php

https://keboola.atlassian.net/browse/CM-731
Retry děláme, tak jen vyhodíme user exception

throw error 502 as user error

---

src/Component.php
src/Extractor/Extractor.php
src/GoogleAnalytics/Client.php
tests/Keboola/GoogleAnalyticsExtractor/GoogleAnalytics/ClientTest.php
tests/functional/DatadirTest.php
tests/functional/get-profile-properties-sync-action-error-handling/source/data/config.json
tests/functional/get-properties-metadata-sync-action/expected-stdout
tests/functional/get-properties-metadata-sync-action/source/data/config.json

https://keboola.atlassian.net/browse/CM-713

New sync action - get properties metadata

---

phpstan.neon
src/Component.php
src/Configuration/ConfigGetPropertiesMetadataDefinition.php
tests/functional/get-properties-metadata-sync-action/source/data/config.json

https://keboolaglobal.slack.com/archives/C055WKGCVS5/p1698324546102869?thread_ts=1697455148.396699&cid=C055WKGCVS5

configDefinition for ACTION_GET_PROPERTIES_METADATA

---

src/GoogleAnalytics/Client.php
tests/Keboola/GoogleAnalyticsExtractor/Extractor/ExtractorTest.php
tests/Keboola/GoogleAnalyticsExtractor/Extractor/ValidatorTest.php

https://keboola.atlassian.net/browse/CM-765

profiles paging

---

src/Extractor/Antisampling/AntisamplingProperty.php

Ověřeno s klientem, že funguje: https://keboola.atlassian.net/browse/SUPPORT-7688?focusedCommentId=124562

fix: remove forgotten var_dump()
